### ISSUE TITLE
Quattro "double bold" in Apple Mail

### ISSUE THREAD

**Issue by Stakker** [iaolo/iA-Fonts#71]
Bold works in normal fashion in Mono and Duo, but for some reason, bolded Quattro looks like it's bolded twice.

What I mean is that it looks like it's the actual bold font and then is additionally fake bolded. Or just massively fake-bolded.

I think this only happens in Apple Mail. (It may be that Apple Mail has some old funky code, but I haven't noticed this happening with other fonts.)

See attached example.
![Shot](https://github.com/iaolo/iA-Fonts/assets/8972595/dcf2757e-521a-4cac-a4a3-ae448dfdbe55)

**Comment by kenmcd** [comment]
Probably related to this issue: https://github.com/iaolo/iA-Fonts/issues/50
The fonts do not appear to have been fixed.

**Comment by Stakker** [comment]
Ahh yeah, probably! I redownloaded the fonts just to be 100% sure I have the latest versions, but nope, the problem is still there.

**Comment by antons** [comment]
This issue will be fixed in the next update. The next update has not been released yet. We’re working on it, and it will be available when we‘re ready.

**Comment by Stakker** [comment]
Good to hear!
